### ISSUE TITLE
سبد خریدش دقیقا کجاست؟

### ISSUE THREAD

**Issue by SalehBagheri** [MehdiSaeedifar/IrisStore#3]
ممنونم بابت این فروشگاه شما!

میخواستم بپرسم که برای این فروشگاه سبد خرید در نظر گرفته نشده؟ یا اینکه بنده پیدا نمیکنم؟

**Comment by MehdiSaeedifar** [comment]
سلام
 سبد خرید را قرار است در نسخه های بعدی اضافه کنم.

**Comment by SalehBagheri** [comment]
خب پس عملا هنوز فروشگاه نشده
