### ISSUE TITLE
dont working pagin mvc

### ISSUE THREAD

**Issue by amir3164** [MehdiSaeedifar/IrisStore#4]
iam use this project but dont work PagedListPager.
PagedListPager  only show one page .dont work next and prev
pleses see this pic:
![sss](https://cloud.githubusercontent.com/assets/10501720/18409680/c050acbc-7762-11e6-926d-799631de2997.png)
![untitled2](https://cloud.githubusercontent.com/assets/10501720/18409681/c2debd5c-7762-11e6-8e07-3a2bcc3bcb57.png)

**Comment by zandiarash** [comment]
I have same problem too

**Comment by MehdiSaeedifar** [comment]
ممنون بابت گزارش.

**Comment by zandiarash** [comment]
من باب یاد آوری : بی زحمت این متن رو کپی کنید تو یه ادیتور ،  با  فشردن هم زمان کنترل سمت راست و شیفت سمت راستی راست چین کنید و بعد بخونید

جناب مهندس سعیدی فر ، ممنون بابت پروژه کامل و جالبی که گیت هاب گذاشتید تا بقیه هم استفاده کنن.
اخیرا دانلود کردم و دارم روش کار میکنم،
قسمت paging  کالا ها کار نمیکنه و دلیلش رو من میدونم اما نتونستم اصلاح کنم.
توی servicelyer فایل product service متد SearchProduct
این خط
            return await productsQuery.Skip((searchModel.PageNumber - 1) \* searchModel.PageSize)
                .Take(searchModel.PageSize)
                .ProjectTo<ProductWidgetViewModel>(null, _mappingEngine).ToListAsync();

باید اینجوری بشه

 return await productsQuery.ProjectTo<ProductWidgetViewModel>(null, _mappingEngine).ToListAsync();

که وقتی topagedlist میشه بفهمه کلا چند صفحه محصول داریم.
اما با این کار هم باگ میخوره چون بعد از اینکه یه بار پیج بعد زدیم و محصولات جدید بصورت ای جکس جایگزین شدن دیگه فایل search-product.js بلا استفاده میشه چون live نیست

شما راه حلی دارید برای این اسکریپت ؟

**Comment by amir3164** [comment]
سلام اقای سعید نتونستی مشکل بالا رو حل کنید؟ با سپاس

**Comment by MehdiSaeedifar** [comment]
سلام

شرمنده ی شرمنده، متاسفانه این روزا خیلی گرفتار هستم.
سعی خودم را می کنم تا هفته ی آینده مشکلش را حل کنم.

**Comment by amir3164** [comment]
سلام مهندس .
فرصت نکردید این باگ که عرض کردیم رو بر طرف کنید /سپاسگذارم

**Comment by MehdiSaeedifar** [comment]
بابت تاخیر عذر خواهی می کنم.

[مشکل ذکر شده برطرف شد.](https://github.com/MehdiSaeedifar/IrisStore/commit/e96f98faf20f86a2b248b9fb14deab22aff121fe) 
ممنون از دوستان بابت گزارش
