### ISSUE TITLE
error on using WebApi 

### ISSUE THREAD

**Issue by ferhat-aksoy** [MehdiSaeedifar/IrisStore#5]
hi dear 
when i install mvc.webapi and create new controller that inherited from ApiController 
and inject dependencies in constructor i got error message that attached  
please check that and say me what must be do thanks
[ErrorText.txt](https://github.com/MehdiSaeedifar/IrisStore/files/663296/ErrorText.txt)

**Comment by MehdiSaeedifar** [comment]
Hi,
Because web api has its own dependency injection mechanism and you should config it separately.
[
More Info](http://www.dotnettips.info/courses/topic/5/3697d84b-8c79-4722-875f-a35920fe88ba)
